apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-platform-backend
  namespace: ml-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-platform-backend
  template:
    metadata:
      labels:
        app: ml-platform-backend
    spec:
      containers:
      - name: backend
        image: ml-platform-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres:5432/mlplatform"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: secret-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: stripe-secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-platform-backend
  namespace: ml-platform
spec:
  selector:
    app: ml-platform-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ml-platform
type: Opaque
stringData:
  secret-key: "your-secret-key-change-in-production-make-it-long-and-random"
  stripe-secret-key: "sk_test_your_stripe_secret_key_here"