// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzsjyrjxqzqiifrdwpvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6c2p5cmp4cXpxaWlmcmR3cHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjE4MDIsImV4cCI6MjA3MjM5NzgwMn0.lqvslQUwLapHv9kT_bw6vLP8VqQeWhJdG8RXE_8E4I4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});